 name: GitHub Actions Build and Deploy Demo
 on:
   push:
     branches:
       - master
 jobs:
   build-and-deploy:
#      strategy:
#        matrix:
#          os: [ubuntu-latest, windows-latest, macOS-latest]
    # runs-on: ubuntu-latest
#      runs-on: ${{ matrix.os }} # 使用的 OS
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Build and Deploy
         uses: JamesIves/github-pages-deploy-action@master
         env:
           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_GP }}
           BRANCH: gh-pages
           FOLDER: build
           BUILD_SCRIPT: yarn && yarn build

